sudo: required
dist: focal
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_2ad4364229b3_key -iv $encrypted_2ad4364229b3_iv -in multi-k8s-412614-65f9fbe63b79.json.enc -out multi-k8s-412614-65f9fbe63b79.json -d
  - CLOUDSDK_PYTHON=python3.8
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-412614-65f9fbe63b79.json
  - gcloud config set project multi-k8s-412614
  - gcloud config set compute/zone us-east5-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t rodmachado/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rodmachado/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
